# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: christnp.github.io
title: Christman's Projects
email: thechristnp@gmail.com
author: Nick Christman
description: > # "Write an awesome description for your new site here. 
  Landing page for projects created by Nick Christman. This includes University
  and personal projects.
copyright: 'Copyright &copy; 2016 Nick Christman. All Rights Reserved.'
credits: 'Credits: Base theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/TheChristman86
  - title: github
    url: https://github.com/christnp
  - title: linkedin
    url: https://www.linkedin.com/in/nicholas-christman-855a24b6
